version: '3.7'

services:
  db:
    image: postgres:10
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - '3000:3000'
    links:
      - db
volumes:
  postgres_data:
